version: '3'
services:

  db:
    image: postgres:14.6-alpine
    container_name: db
    networks: 
      - net
    volumes:
      - ./data/db:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped 
    

  api:
    build: 
      context: ./task
      
    command: gunicorn  config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: unless-stopped
    networks: 
      - net
    container_name: api
    volumes:
      - api_vol:/task
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


volumes:
  api_vol:

networks:
  net:
    driver: bridge
